apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flight-planner.fullname" . }}-frontend
  labels:
    {{- include "flight-planner.labels" . | nindent 4 }}
    {{- include "flight-planner.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "flight-planner.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flight-planner.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
