apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-planner.fullname" . }}-frontend
  labels:
    {{- include "flight-planner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "flight-planner.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
