{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-planner.fullname" . }}-postgres
  labels:
    {{- include "flight-planner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "flight-planner.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
{{- end }}
