apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-planner.fullname" . }}-secret
  labels:
    {{- include "flight-planner.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAIP_API_KEY: {{ .Values.openaipApiKey | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.username .Values.postgres.password (include "flight-planner.fullname" .) .Values.postgres.database | quote }}
